# Generated by Django 5.1.2 on 2024-11-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta_Bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField()),
                ('banco', models.CharField(choices=[('ING', 'Banco ING'), ('UNICAJA', 'Banco UNICAJA'), ('CAIXA', 'Banco CAIXA'), ('BBVA', 'Banco BBVA')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MiniJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('fecha_lanzamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('cuenta_bancaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria_usuario', to='examen.cuenta_bancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=50)),
                ('fecha_hora', models.DateField()),
                ('usuario_voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ususario_que_voto', to='examen.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Votos_de_los_minijuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_minijuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.minijuego')),
                ('id_voto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examen.voto')),
            ],
        ),
        migrations.AddField(
            model_name='voto',
            name='minijuego_voto',
            field=models.ManyToManyField(related_name='minijuego_que_se_voto', through='examen.Votos_de_los_minijuegos', to='examen.minijuego'),
        ),
    ]
